spring:
  datasource:
    username: root
    password: rewa@2018
    url: jdbc:mysql://192.168.10.139:3306/test?autoReconnect=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8